In [23]:
import os
import pandas as pd

# Загрузка набора данных
OUTPUT_FILE = os.path.join(os.getcwd(), "IsaacLab", "source", "standalone", "grasp_dataset.csv")

db = pd.read_csv(OUTPUT_FILE)
# Вывод данных
print(db.head(300))

     exp_id     object_name shape_type  density    volume     mass   size_x  \
0         1           Stone       cube   2795.1  0.000001  0.00283  0.01004
1         2  Plastic bottle   cylinder   1444.2  0.001675  2.41965  0.27434
2         3     Chicken egg  ellipsoid   2050.2  0.000155  0.31858  0.07807
3         4     Rubber ball     sphere   1335.6  0.000232  0.30983  0.07623
4         5          Tomato     sphere   1074.3  0.000229  0.24606  0.07591
..      ...             ...        ...      ...       ...      ...      ...
295     296     Chicken egg  ellipsoid   2779.6  0.000094  0.26245  0.06613
296     297         Tin can   cylinder   7772.7  0.000367  2.85426  0.09597
297     298     Chicken egg  ellipsoid   2442.1  0.000142  0.34580  0.07569
298     299  Plastic bottle   cylinder   1225.4  0.002032  2.49031  0.29258
299     300          Tomato     sphere    957.9  0.000152  0.14570  0.06623

      size_y   size_z  surface_area  ...  transparency  hardness  \
0    0.01004  0.01004      0.000604  ...        opaque       7.0
1    0.08818  0.08818      0.088213  ...   transparent       2.0
2    0.04461  0.04461      0.020899  ...        opaque       3.0
3    0.07623  0.07623      0.018258  ...        opaque       0.1
4    0.07591  0.07591      0.018103  ...        opaque       0.5
..       ...      ...           ...  ...           ...       ...
295  0.03779  0.03779      0.014992  ...        opaque       3.0
296  0.06980  0.06980      0.028697  ...        opaque       4.5
297  0.04325  0.04325      0.019643  ...        opaque       3.0
298  0.09404  0.09404      0.100334  ...   transparent       2.0
299  0.06623  0.06623      0.013779  ...        opaque       0.5

     grasp_force_N  contact_stress  stress_ratio  outcome label_success  \
0           32.342         70504.5       0.00082  success             1
1           34.543        165487.3       0.60348  success             1
2           16.992         89008.9       1.84515    crush             0
3           17.328        115276.7       2.71470    crush             0
4            5.928         35681.3       1.17566    crush             0
..             ...             ...           ...      ...           ...
295         38.422        108803.8       2.42079    crush             0
296        103.126        601903.0       1.40051  success             1
297         38.628        126775.7       2.39802    crush             0
298        545.165       3408824.2      11.05505    crush             0
299          5.927         28504.7       1.11292    crush             0

    label_crush  label_drop  duration_sec
0             0           0          8.65
1             0           0          6.52
2             1           0          3.19
3             1           0          2.94
4             1           0          0.78
..          ...         ...           ...
295           1           0          2.63
296           0           0          2.89
297           1           0          3.54
298           1           0          1.32
299           1           0          0.95

[300 rows x 27 columns]

In [24]:
# Информация по столбцам
db.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354823 entries, 0 to 354822
Data columns (total 27 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   exp_id          354823 non-null  int64
 1   object_name     354823 non-null  object
 2   shape_type      354823 non-null  object
 3   density         354823 non-null  float64
 4   volume          354823 non-null  float64
 5   mass            354823 non-null  float64
 6   size_x          354823 non-null  float64
 7   size_y          354823 non-null  float64
 8   size_z          354823 non-null  float64
 9   surface_area    354823 non-null  float64
 10  contact_area    354823 non-null  float64
 11  young_modulus   354823 non-null  float64
 12  poisson_ratio   354823 non-null  float64
 13  friction        354823 non-null  float64
 14  stress_limit    354823 non-null  float64
 15  safe_force      354823 non-null  int64
 16  color           354823 non-null  object
 17  transparency    354823 non-null  object
 18  hardness        354823 non-null  float64
 19  grasp_force_N   354823 non-null  float64
 20  contact_stress  354823 non-null  float64
 21  stress_ratio    354823 non-null  float64
 22  outcome         354823 non-null  object
 23  label_success   354823 non-null  int64
 24  label_crush     354823 non-null  int64
 25  label_drop      354823 non-null  int64
 26  duration_sec    354823 non-null  float64
dtypes: float64(17), int64(5), object(5)
memory usage: 73.1+ MB

In [25]:
# Аналитика по столбцам
db.describe()

,exp_id,density,volume,mass,size_x,size_y,size_z,surface_area,contact_area,young_modulus,...,stress_limit,safe_force,hardness,grasp_force_N,contact_stress,stress_ratio,label_success,label_crush,label_drop,duration_sec
count,354823.00000,354823.000000,3.548230e+05,354823.000000,354823.000000,354823.000000,354823.000000,354823.000000,354823.000000,3.548230e+05,...,3.548230e+05,354823.000000,354823.000000,354823.000000,3.548230e+05,354823.000000,354823.000000,354823.000000,354823.000000,354823.00000
mean,177412.00000,2399.921928,4.744397e-04,1.166687,0.113873,0.058463,0.058463,0.030405,0.000200,3.612827e+10,...,1.224696e+07,39.687630,2.475907,156.626263,5.914798e+05,2.604503,0.461481,0.517266,0.021253,1.43251
std,102428.72162,2235.191739,6.713657e-04,1.775118,0.085175,0.027356,0.027356,0.030419,0.000046,6.858728e+10,...,2.984710e+07,39.087778,2.368527,955.237105,1.610449e+06,5.643892,0.498515,0.499702,0.144226,0.79677
min,1.00000,578.300000,6.100000e-07,0.001070,0.008500,0.008500,0.008500,0.000434,0.000120,2.871500e+04,...,1.705650e+04,6.000000,0.100000,-0.064000,2.201840e+04,0.000580,0.000000,0.000000,0.000000,0.33000
25%,88706.50000,1051.700000,1.253600e-04,0.157320,0.065510,0.039220,0.039220,0.013898,0.000160,2.134640e+05,...,3.321330e+04,6.000000,0.300000,9.600000,5.445725e+04,1.058355,0.000000,0.000000,0.000000,0.77000
50%,177412.00000,1342.700000,2.027600e-04,0.250720,0.079720,0.065380,0.065380,0.019856,0.000200,2.494191e+09,...,4.979610e+04,10.000000,2.000000,17.328000,7.955770e+04,1.462240,0.000000,1.000000,0.000000,1.37000
75%,266117.50000,2485.900000,4.438000e-04,1.886180,0.159560,0.080100,0.080100,0.033546,0.000240,4.612308e+10,...,4.154307e+05,90.000000,4.500000,91.208500,2.587504e+05,2.265640,1.000000,1.000000,0.000000,1.87000
max,354823.00000,10410.900000,3.078010e-03,9.125190,0.336000,0.108000,0.108000,0.132323,0.000280,2.839207e+11,...,1.239731e+08,100.000000,7.000000,145705.514000,5.364198e+07,379.126420,1.000000,1.000000,1.000000,19.18000

In [26]:
if "outcome" not in db.columns:
    print("В файле отсутствует колонка 'outcome'")
    exit(1)

# ──────────────── Статистика ────────────────
counts = db["outcome"].value_counts()
percents = db["outcome"].value_counts(normalize=True) * 100
total = len(db)

print("\n" + "="*50)
print(f"Статистика исходов (всего экспериментов: {total})")
print("="*50)

for outcome in ["success", "drop", "crush", "marginal"]:
    if outcome in counts.index:
        cnt = counts[outcome]
        pct = percents[outcome]
        print(f"{outcome:10} : {cnt:5d} шт  →  {pct:5.1f}%")
    else:
        print(f"{outcome:10} :     0 шт  →   0.0%")

print("-"*50)
print(f"Всего записей: {total}")
print("="*50 + "\n")

==================================================
Статистика исходов (всего экспериментов: 354823)
==================================================
success    : 163744 шт  →   46.1%
drop       :  7541 шт  →    2.1%
crush      : 183538 шт  →   51.7%
marginal   :     0 шт  →   0.0%
--------------------------------------------------
Всего записей: 354823
==================================================

In [27]:
# выбрать только нужные колонки
columns = ["exp_id", "object_name", "grasp_force_N", "outcome"]
db_selected = db[columns]

print(db_selected.head(300))

     exp_id     object_name  grasp_force_N  outcome
0         1           Stone         32.342  success
1         2  Plastic bottle         34.543  success
2         3     Chicken egg         16.992    crush
3         4     Rubber ball         17.328    crush
4         5          Tomato          5.928    crush
..      ...             ...            ...      ...
295     296     Chicken egg         38.422    crush
296     297         Tin can        103.126  success
297     298     Chicken egg         38.628    crush
298     299  Plastic bottle        545.165    crush
299     300          Tomato          5.927    crush

[300 rows x 4 columns]

In [28]:
# Выберите нужные колонки
columns = ["exp_id", "object_name", "grasp_force_N", "outcome"]
df_selected = db[columns]

# Статистика по каждому объекту
stats = df_selected.groupby("object_name")["outcome"].value_counts().unstack(fill_value=0)
print(stats)

# Добавим общее количество экспериментов для каждого объекта
stats["total"] = stats.sum(axis=1)
print(stats)

# Процентное соотношение
stats_pct = stats.div(stats["total"], axis=0) * 100
print(stats_pct.round(1))

outcome         crush  drop  success
object_name
Chicken egg     40555   109    10943
Cucumber        30608     0    19877
Plastic bottle  33893  1291    15370
Rubber ball      6786     0    44478
Stone              23     0    50556
Tin can         26464  6141    16917
Tomato          45209     0     5603
outcome         crush  drop  success  total
object_name
Chicken egg     40555   109    10943  51607
Cucumber        30608     0    19877  50485
Plastic bottle  33893  1291    15370  50554
Rubber ball      6786     0    44478  51264
Stone              23     0    50556  50579
Tin can         26464  6141    16917  49522
Tomato          45209     0     5603  50812
outcome         crush  drop  success  total
object_name
Chicken egg      78.6   0.2     21.2  100.0
Cucumber         60.6   0.0     39.4  100.0
Plastic bottle   67.0   2.6     30.4  100.0
Rubber ball      13.2   0.0     86.8  100.0
Stone             0.0   0.0    100.0  100.0
Tin can          53.4  12.4     34.2  100.0
Tomato           89.0   0.0     11.0  100.0

In [29]:
data_name_number = db.select_dtypes(include='number').columns
print(f'Числовые столбцы: {data_name_number}')

Числовые столбцы: Index(['exp_id', 'density', 'volume', 'mass', 'size_x', 'size_y', 'size_z',
       'surface_area', 'contact_area', 'young_modulus', 'poisson_ratio',
       'friction', 'stress_limit', 'safe_force', 'hardness', 'grasp_force_N',
       'contact_stress', 'stress_ratio', 'label_success', 'label_crush',
       'label_drop', 'duration_sec'],
      dtype='object')

In [30]:
min_num = (db.select_dtypes(include='number')<0).sum().sum()
print(f'Число строк с отрицательными значениями: {min_num}')

Число строк с отрицательными значениями: 5

In [31]:
min_str = (db.select_dtypes(include='number')<0).any(axis = 1)
print('Число строк с отрицательными значениями:')
print(db[min_str])

Число строк с отрицательными значениями:
        exp_id  object_name shape_type  density    volume     mass   size_x  \
35456    35457  Chicken egg  ellipsoid   2622.0  0.000181  0.47349  0.08208
230274  230275  Chicken egg  ellipsoid   2622.0  0.000181  0.47349  0.08208
270274  270275  Chicken egg  ellipsoid   2622.0  0.000181  0.47349  0.08208
310274  310275  Chicken egg  ellipsoid   2622.0  0.000181  0.47349  0.08208
350274  350275  Chicken egg  ellipsoid   2622.0  0.000181  0.47349  0.08208

        size_y  size_z  surface_area  ...  transparency  hardness  \
35456   0.0469  0.0469        0.0231  ...        opaque       3.0
230274  0.0469  0.0469        0.0231  ...        opaque       3.0
270274  0.0469  0.0469        0.0231  ...        opaque       3.0
310274  0.0469  0.0469        0.0231  ...        opaque       3.0
350274  0.0469  0.0469        0.0231  ...        opaque       3.0

        grasp_force_N  contact_stress  stress_ratio  outcome label_success  \
35456          -0.055         48931.7       1.14386     drop             0
230274         -0.064         48931.7       1.14386     drop             0
270274         -0.048         48931.7       1.14386     drop             0
310274         -0.064         48931.7       1.14386     drop             0
350274         -0.043         48931.7       1.14386     drop             0

       label_crush  label_drop  duration_sec
35456            0           1          0.62
230274           0           1          0.55
270274           0           1          0.61
310274           0           1          0.57
350274           0           1          0.55

[5 rows x 27 columns]

In [32]:
db.head(30)

,exp_id,object_name,shape_type,density,volume,mass,size_x,size_y,size_z,surface_area,...,transparency,hardness,grasp_force_N,contact_stress,stress_ratio,outcome,label_success,label_crush,label_drop,duration_sec
0,1,Stone,cube,2795.1,1.010000e-06,0.00283,0.01004,0.01004,0.01004,0.000604,...,opaque,7.0,32.342,70504.5,0.00082,success,1,0,0,8.65
1,2,Plastic bottle,cylinder,1444.2,1.675400e-03,2.41965,0.27434,0.08818,0.08818,0.088213,...,transparent,2.0,34.543,165487.3,0.60348,success,1,0,0,6.52
2,3,Chicken egg,ellipsoid,2050.2,1.553900e-04,0.31858,0.07807,0.04461,0.04461,0.020899,...,opaque,3.0,16.992,89008.9,1.84515,crush,0,1,0,3.19
3,4,Rubber ball,sphere,1335.6,2.319800e-04,0.30983,0.07623,0.07623,0.07623,0.018258,...,opaque,0.1,17.328,115276.7,2.71470,crush,0,1,0,2.94
4,5,Tomato,sphere,1074.3,2.290400e-04,0.24606,0.07591,0.07591,0.07591,0.018103,...,opaque,0.5,5.928,35681.3,1.17566,crush,0,1,0,0.78
5,6,Chicken egg,ellipsoid,2214.9,8.720000e-05,0.19315,0.06440,0.03680,0.03680,0.014219,...,opaque,3.0,16.845,89583.8,1.85084,crush,0,1,0,3.33
6,7,Chicken egg,ellipsoid,2413.0,1.426400e-04,0.34419,0.07588,0.04336,0.04336,0.019739,...,opaque,3.0,23.599,82720.8,1.56280,crush,0,1,0,2.68
7,8,Stone,cube,2823.1,1.010000e-06,0.00285,0.01003,0.01003,0.01003,0.000603,...,opaque,7.0,84.554,105004.8,0.00136,success,1,0,0,4.19
8,9,Stone,cube,2762.7,1.420000e-06,0.00393,0.01124,0.01124,0.01124,0.000758,...,opaque,7.0,88.768,128920.6,0.00157,success,1,0,0,3.83
9,10,Cucumber,cylinder,1001.2,1.591000e-04,0.15930,0.15410,0.03626,0.03626,0.019618,...,opaque,0.3,5.928,35233.0,1.18611,success,1,0,0,0.84
10,11,Tin can,cylinder,6932.1,3.915000e-04,2.71396,0.09804,0.07130,0.07130,0.029949,...,opaque,4.5,296.986,1214170.3,2.38791,crush,0,1,0,3.26
11,12,Stone,cube,2353.0,8.400000e-07,0.00199,0.00945,0.00945,0.00945,0.000536,...,opaque,7.0,72.540,81474.9,0.00092,success,1,0,0,4.06
12,13,Stone,cube,2660.5,1.340000e-06,0.00356,0.01102,0.01102,0.01102,0.000728,...,opaque,7.0,72.529,92896.3,0.00122,success,1,0,0,4.11
13,14,Plastic bottle,cylinder,1387.8,1.602970e-03,2.22463,0.27033,0.08689,0.08689,0.085652,...,transparent,2.0,1444.991,6784955.7,24.92611,crush,0,1,0,1.55
14,15,Tomato,sphere,898.4,2.992200e-04,0.26883,0.08298,0.08298,0.08298,0.021635,...,opaque,0.5,17.328,64165.0,1.65623,crush,0,1,0,2.95
15,16,Stone,cube,2388.6,8.400000e-07,0.00201,0.00943,0.00943,0.00943,0.000534,...,opaque,7.0,73.915,65788.7,0.00070,success,1,0,0,4.76
16,17,Tomato,sphere,994.6,2.295700e-04,0.22834,0.07597,0.07597,0.07597,0.018131,...,opaque,0.5,5.927,37794.3,1.32602,crush,0,1,0,0.88
17,18,Stone,cube,2386.4,9.400000e-07,0.00224,0.00980,0.00980,0.00980,0.000576,...,opaque,7.0,37.497,142076.9,0.00161,success,1,0,0,4.12
18,19,Chicken egg,ellipsoid,1930.4,7.267000e-05,0.14028,0.06060,0.03463,0.03463,0.012591,...,opaque,3.0,6.820,65897.4,1.29719,success,1,0,0,2.85
19,20,Chicken egg,ellipsoid,2109.6,1.574400e-04,0.33213,0.07841,0.04481,0.04481,0.021082,...,opaque,3.0,8.957,64203.4,1.26096,success,1,0,0,3.51
20,21,Stone,cube,2500.4,7.400000e-07,0.00185,0.00904,0.00904,0.00904,0.000490,...,opaque,7.0,74.916,62897.2,0.00070,success,1,0,0,5.92
21,22,Plastic bottle,cylinder,1528.6,1.112870e-03,1.70114,0.23937,0.07694,0.07694,0.067156,...,transparent,2.0,303.687,1314194.8,4.40210,crush,0,1,0,4.22
22,23,Tin can,cylinder,6678.7,7.367200e-04,4.92035,0.12104,0.08803,0.08803,0.045649,...,opaque,4.5,261.346,1156098.0,2.33497,crush,0,1,0,4.01
23,24,Plastic bottle,cylinder,1310.0,2.879950e-03,3.77275,0.32863,0.10563,0.10563,0.126584,...,transparent,2.0,147.681,789491.6,2.60804,crush,0,1,0,1.19
24,25,Chicken egg,ellipsoid,1878.0,1.622600e-04,0.30473,0.07921,0.04526,0.04526,0.021510,...,opaque,3.0,11.738,70013.8,1.51040,success,1,0,0,3.36
25,26,Tin can,cylinder,7292.3,6.624700e-04,4.83094,0.11683,0.08497,0.08497,0.042527,...,opaque,4.5,286.101,1792000.1,4.66687,crush,0,1,0,3.51
26,27,Plastic bottle,cylinder,1183.0,1.242450e-03,1.46983,0.24832,0.07982,0.07982,0.072273,...,transparent,2.0,107.342,750541.9,2.77573,crush,0,1,0,1.70
27,28,Plastic bottle,cylinder,1322.1,1.525550e-03,2.01688,0.26590,0.08547,0.08547,0.082871,...,transparent,2.0,1515.294,11788402.0,38.40307,crush,0,1,0,1.38
28,29,Plastic bottle,cylinder,1347.1,1.582360e-03,2.13163,0.26916,0.08652,0.08652,0.084916,...,transparent,2.0,100.719,629877.4,2.12022,crush,0,1,0,1.45
29,30,Tomato,sphere,888.8,1.171400e-04,0.10411,0.06071,0.06071,0.06071,0.011578,...,opaque,0.5,10.462,41032.5,1.65679,crush,0,1,0,0.87

In [33]:
db.tail(30)

,exp_id,object_name,shape_type,density,volume,mass,size_x,size_y,size_z,surface_area,...,transparency,hardness,grasp_force_N,contact_stress,stress_ratio,outcome,label_success,label_crush,label_drop,duration_sec
354793,354794,Rubber ball,sphere,1171.7,1.223000e-04,0.14329,0.06158,0.06158,0.06158,0.011915,...,opaque,0.1,9.251,53897.7,1.23671,success,1,0,0,1.27
354794,354795,Tomato,sphere,879.7,2.509400e-04,0.22075,0.07826,0.07826,0.07826,0.019239,...,opaque,0.5,17.328,66047.9,2.35556,crush,0,1,0,1.69
354795,354796,Chicken egg,ellipsoid,1969.2,1.234300e-04,0.24306,0.07230,0.04132,0.04132,0.017924,...,opaque,3.0,8.121,66080.3,1.13653,crush,0,1,0,1.21
354796,354797,Tin can,cylinder,9533.5,7.762400e-04,7.40028,0.12317,0.08958,0.08958,0.047267,...,opaque,4.5,230.586,1438894.2,3.17660,crush,0,1,0,1.51
354797,354798,Tomato,sphere,1248.2,2.139000e-04,0.26698,0.07420,0.07420,0.07420,0.017296,...,opaque,0.5,10.649,48104.5,1.70810,crush,0,1,0,0.62
354798,354799,Plastic bottle,cylinder,1557.7,2.250040e-03,3.50478,0.30268,0.09729,0.09729,0.107378,...,transparent,2.0,519.050,2082936.1,9.05771,crush,0,1,0,0.73
354799,354800,Tin can,cylinder,6995.8,6.198900e-04,4.33665,0.11427,0.08311,0.08311,0.040685,...,opaque,4.5,106.759,665635.6,1.40553,success,1,0,0,1.52
354800,354801,Cucumber,cylinder,838.5,3.043300e-04,0.25518,0.19128,0.04501,0.04501,0.030229,...,opaque,0.3,9.712,56986.1,1.90133,crush,0,1,0,0.61
354801,354802,Stone,cube,2708.8,1.240000e-06,0.00337,0.01076,0.01076,0.01076,0.000694,...,opaque,7.0,91.834,74904.4,0.00106,success,1,0,0,2.11
354802,354803,Stone,cube,2314.5,8.000000e-07,0.00185,0.00928,0.00928,0.00928,0.000516,...,opaque,7.0,55.387,79477.0,0.00092,success,1,0,0,2.14
354803,354804,Tomato,sphere,899.6,1.759600e-04,0.15829,0.06952,0.06952,0.06952,0.015185,...,opaque,0.5,10.401,52630.6,1.67783,crush,0,1,0,1.26
354804,354805,Tin can,cylinder,7648.4,5.464500e-04,4.17944,0.10957,0.07969,0.07969,0.037404,...,opaque,4.5,172.638,973880.3,2.30048,crush,0,1,0,1.61
354805,354806,Plastic bottle,cylinder,1540.1,1.919960e-03,2.95700,0.28709,0.09228,0.09228,0.096601,...,transparent,2.0,619.313,2303976.6,7.53047,crush,0,1,0,0.84
354806,354807,Plastic bottle,cylinder,1230.1,1.340010e-03,1.64841,0.25465,0.08185,0.08185,0.076008,...,transparent,2.0,1606.475,8323471.2,27.70289,crush,0,1,0,0.96
354807,354808,Tomato,sphere,1006.4,1.694000e-04,0.17049,0.06865,0.06865,0.06865,0.014806,...,opaque,0.5,17.328,82574.4,2.63782,crush,0,1,0,1.50
354808,354809,Tin can,cylinder,8793.5,6.250600e-04,5.49645,0.11459,0.08334,0.08334,0.040911,...,opaque,4.5,131.598,485618.3,1.14849,success,1,0,0,1.50
354809,354810,Stone,cube,2550.2,1.490000e-06,0.00381,0.01143,0.01143,0.01143,0.000784,...,opaque,7.0,72.540,62903.8,0.00068,success,1,0,0,2.15
354810,354811,Cucumber,cylinder,1090.4,2.933700e-04,0.31989,0.18896,0.04446,0.04446,0.029499,...,opaque,0.3,5.928,41278.4,1.36579,crush,0,1,0,0.71
354811,354812,Tomato,sphere,1087.8,2.140900e-04,0.23288,0.07422,0.07422,0.07422,0.017307,...,opaque,0.5,5.928,39399.1,1.46405,crush,0,1,0,0.60
354812,354813,Plastic bottle,cylinder,1279.1,2.278770e-03,2.91469,0.30396,0.09770,0.09770,0.108290,...,transparent,2.0,105.617,382092.7,1.27825,success,1,0,0,0.81
354813,354814,Plastic bottle,cylinder,1269.8,2.297060e-03,2.91687,0.30477,0.09796,0.09796,0.108869,...,transparent,2.0,209.617,1026482.0,3.28830,crush,0,1,0,0.76
354814,354815,Plastic bottle,cylinder,1348.0,1.482410e-03,1.99825,0.26337,0.08466,0.08466,0.081301,...,transparent,2.0,1521.120,8780183.3,33.97507,crush,0,1,0,0.86
354815,354816,Cucumber,cylinder,869.1,2.017400e-04,0.17533,0.16679,0.03924,0.03924,0.022982,...,opaque,0.3,7.722,33440.3,1.04694,success,1,0,0,1.18
354816,354817,Tomato,sphere,1028.9,2.313500e-04,0.23803,0.07617,0.07617,0.07617,0.018225,...,opaque,0.5,17.328,66754.0,2.58582,crush,0,1,0,1.55
354817,354818,Rubber ball,sphere,1029.7,3.044400e-04,0.31347,0.08346,0.08346,0.08346,0.021885,...,opaque,0.1,17.328,89806.5,2.25109,crush,0,1,0,1.56
354818,354819,Stone,cube,2795.1,1.010000e-06,0.00283,0.01004,0.01004,0.01004,0.000604,...,opaque,7.0,98.176,70504.5,0.00082,success,1,0,0,11.65
354819,354820,Plastic bottle,cylinder,1444.2,1.675400e-03,2.41965,0.27434,0.08818,0.08818,0.088213,...,transparent,2.0,36.734,175983.9,0.64176,success,1,0,0,8.87
354820,354821,Chicken egg,ellipsoid,2050.2,1.553900e-04,0.31858,0.07807,0.04461,0.04461,0.020899,...,opaque,3.0,33.757,89008.9,1.84515,crush,0,1,0,4.01
354821,354822,Rubber ball,sphere,1335.6,2.319800e-04,0.30983,0.07623,0.07623,0.07623,0.018258,...,opaque,0.1,17.328,115276.7,2.71470,crush,0,1,0,5.18
354822,354823,Tomato,sphere,1074.3,2.290400e-04,0.24606,0.07591,0.07591,0.07591,0.018103,...,opaque,0.5,5.928,35681.3,1.17566,crush,0,1,0,1.43