In [46]:
import sys
from pathlib import Path
import shutil
import pandas as pd

In [47]:
path_file = r"IsaacLab\source\standalone\grasp_dataset.csv"
path_file_in = r"IsaacLab\source_project_main\grasp_dataset.csv"
file_path = Path(path_file)
file_path_in = Path(path_file_in)
if file_path.is_file():
   print(f"Файл найден: {file_path}")
   if file_path_in.is_file():
      print(f"Файл найден: {file_path_in}")
   else:
      shutil.copy(path_file, path_file_in)
else:
   sys.exit()

Файл найден: IsaacLab\source\standalone\grasp_dataset.csv
Файл найден: IsaacLab\source_project_main\grasp_dataset.csv

In [48]:
df = pd.read_csv(path_file_in)

In [49]:
df.head()

,exp_id,object_name,shape_type,density,volume,mass,size_x,size_y,size_z,surface_area,...,transparency,hardness,grasp_force_N,contact_stress,stress_ratio,outcome,label_success,label_crush,label_drop,duration_sec
0,1,Stone,cube,2795.1,0.000001,0.00283,0.01004,0.01004,0.01004,0.000604,...,opaque,7.0,32.342,70504.5,0.00082,success,1,0,0,8.65
1,2,Plastic bottle,cylinder,1444.2,0.001675,2.41965,0.27434,0.08818,0.08818,0.088213,...,transparent,2.0,34.543,165487.3,0.60348,success,1,0,0,6.52
2,3,Chicken egg,ellipsoid,2050.2,0.000155,0.31858,0.07807,0.04461,0.04461,0.020899,...,opaque,3.0,16.992,89008.9,1.84515,crush,0,1,0,3.19
3,4,Rubber ball,sphere,1335.6,0.000232,0.30983,0.07623,0.07623,0.07623,0.018258,...,opaque,0.1,17.328,115276.7,2.71470,crush,0,1,0,2.94
4,5,Tomato,sphere,1074.3,0.000229,0.24606,0.07591,0.07591,0.07591,0.018103,...,opaque,0.5,5.928,35681.3,1.17566,crush,0,1,0,0.78

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369828 entries, 0 to 369827
Data columns (total 27 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   exp_id          369828 non-null  int64
 1   object_name     369828 non-null  object
 2   shape_type      369828 non-null  object
 3   density         369828 non-null  float64
 4   volume          369828 non-null  float64
 5   mass            369828 non-null  float64
 6   size_x          369828 non-null  float64
 7   size_y          369828 non-null  float64
 8   size_z          369828 non-null  float64
 9   surface_area    369828 non-null  float64
 10  contact_area    369828 non-null  float64
 11  young_modulus   369828 non-null  float64
 12  poisson_ratio   369828 non-null  float64
 13  friction        369828 non-null  float64
 14  stress_limit    369828 non-null  float64
 15  safe_force      369828 non-null  int64
 16  color           369828 non-null  object
 17  transparency    369828 non-null  object
 18  hardness        369828 non-null  float64
 19  grasp_force_N   369828 non-null  float64
 20  contact_stress  369828 non-null  float64
 21  stress_ratio    369828 non-null  float64
 22  outcome         369828 non-null  object
 23  label_success   369828 non-null  int64
 24  label_crush     369828 non-null  int64
 25  label_drop      369828 non-null  int64
 26  duration_sec    369828 non-null  float64
dtypes: float64(17), int64(5), object(5)
memory usage: 76.2+ MB

In [51]:
df.columns

Index(['exp_id', 'object_name', 'shape_type', 'density', 'volume', 'mass',
       'size_x', 'size_y', 'size_z', 'surface_area', 'contact_area',
       'young_modulus', 'poisson_ratio', 'friction', 'stress_limit',
       'safe_force', 'color', 'transparency', 'hardness', 'grasp_force_N',
       'contact_stress', 'stress_ratio', 'outcome', 'label_success',
       'label_crush', 'label_drop', 'duration_sec'],
      dtype='object')

In [52]:
df.isnull().sum()

exp_id            0
object_name       0
shape_type        0
density           0
volume            0
mass              0
size_x            0
size_y            0
size_z            0
surface_area      0
contact_area      0
young_modulus     0
poisson_ratio     0
friction          0
stress_limit      0
safe_force        0
color             0
transparency      0
hardness          0
grasp_force_N     0
contact_stress    0
stress_ratio      0
outcome           0
label_success     0
label_crush       0
label_drop        0
duration_sec      0
dtype: int64

In [53]:
df.describe()

,exp_id,density,volume,mass,size_x,size_y,size_z,surface_area,contact_area,young_modulus,...,stress_limit,safe_force,hardness,grasp_force_N,contact_stress,stress_ratio,label_success,label_crush,label_drop,duration_sec
count,369828.000000,369828.000000,3.698280e+05,369828.000000,369828.000000,369828.000000,369828.000000,369828.000000,369828.000000,3.698280e+05,...,3.698280e+05,369828.000000,369828.000000,369828.000000,3.698280e+05,369828.000000,369828.000000,369828.000000,369828.000000,369828.000000
mean,184914.500000,2400.208544,4.744327e-04,1.166899,0.113886,0.058470,0.058470,0.030408,0.000200,3.613474e+10,...,1.222729e+07,39.672875,2.475292,156.812132,5.907288e+05,2.603691,0.461517,0.517181,0.021302,1.418241
std,106760.292014,2235.431008,6.712019e-04,1.775143,0.085156,0.027347,0.027347,0.030412,0.000046,6.860750e+10,...,2.982593e+07,39.081055,2.367574,984.566375,1.607444e+06,5.658935,0.498518,0.499705,0.144389,0.790929
min,1.000000,578.300000,6.100000e-07,0.001070,0.008500,0.008500,0.008500,0.000434,0.000120,2.871500e+04,...,1.705650e+04,6.000000,0.100000,-0.064000,2.201840e+04,0.000580,0.000000,0.000000,0.000000,0.330000
25%,92457.750000,1051.700000,1.253600e-04,0.157430,0.065530,0.039230,0.039230,0.013906,0.000160,2.134909e+05,...,3.322110e+04,6.000000,0.300000,9.599000,5.445030e+04,1.058460,0.000000,0.000000,0.000000,0.760000
50%,184914.500000,1342.900000,2.027700e-04,0.250770,0.079720,0.065390,0.065390,0.019856,0.000200,2.494451e+09,...,4.978690e+04,10.000000,2.000000,17.328000,7.955875e+04,1.462240,0.000000,1.000000,0.000000,1.350000
75%,277371.250000,2485.700000,4.436900e-04,1.887640,0.159560,0.080100,0.080100,0.033547,0.000240,4.611908e+10,...,4.152162e+05,90.000000,4.500000,91.171250,2.587565e+05,2.264485,1.000000,1.000000,0.000000,1.850000
max,369828.000000,10410.900000,3.078010e-03,9.125190,0.336000,0.108000,0.108000,0.132323,0.000280,2.839207e+11,...,1.239731e+08,100.000000,7.000000,145705.514000,5.364198e+07,379.126420,1.000000,1.000000,1.000000,19.180000

In [54]:
num_negative = (df['grasp_force_N'] < 0).sum()
print(f"Число отрицательных строк: {num_negative}")
df[df['grasp_force_N'] < 0].head()

Число отрицательных строк: 5

,exp_id,object_name,shape_type,density,volume,mass,size_x,size_y,size_z,surface_area,...,transparency,hardness,grasp_force_N,contact_stress,stress_ratio,outcome,label_success,label_crush,label_drop,duration_sec
35456,35457,Chicken egg,ellipsoid,2622.0,0.000181,0.47349,0.08208,0.0469,0.0469,0.0231,...,opaque,3.0,-0.055,48931.7,1.14386,drop,0,0,1,0.62
230274,230275,Chicken egg,ellipsoid,2622.0,0.000181,0.47349,0.08208,0.0469,0.0469,0.0231,...,opaque,3.0,-0.064,48931.7,1.14386,drop,0,0,1,0.55
270274,270275,Chicken egg,ellipsoid,2622.0,0.000181,0.47349,0.08208,0.0469,0.0469,0.0231,...,opaque,3.0,-0.048,48931.7,1.14386,drop,0,0,1,0.61
310274,310275,Chicken egg,ellipsoid,2622.0,0.000181,0.47349,0.08208,0.0469,0.0469,0.0231,...,opaque,3.0,-0.064,48931.7,1.14386,drop,0,0,1,0.57
350274,350275,Chicken egg,ellipsoid,2622.0,0.000181,0.47349,0.08208,0.0469,0.0469,0.0231,...,opaque,3.0,-0.043,48931.7,1.14386,drop,0,0,1,0.55

In [55]:
df = df[df['grasp_force_N'] >= 0]

In [56]:
num_negative = (df['grasp_force_N'] < 0).sum()
print(f"Число отрицательных строк: {num_negative}")
df[df['grasp_force_N'] < 0].head()

Число отрицательных строк: 0

Empty DataFrame
Columns: [exp_id, object_name, shape_type, density, volume, mass, size_x, size_y, size_z, surface_area, contact_area, young_modulus, poisson_ratio, friction, stress_limit, safe_force, color, transparency, hardness, grasp_force_N, contact_stress, stress_ratio, outcome, label_success, label_crush, label_drop, duration_sec]
Index: []

[0 rows x 27 columns]

In [57]:
sum_all = len(df)
print("\n" + "="*50)
print(f"Статистика исходов (всего экспериментов: {sum_all})")
print("="*50)
counts = df["outcome"].value_counts()
percents = df["outcome"].value_counts()/sum_all * 100
for outcome in ["success", "drop", "crush", "marginal"]:
    if outcome in counts.index:
        cnt = counts[outcome]
        pct = percents[outcome]
        print(f"{outcome:10} : {cnt:5d} шт  →  {pct:5.1f}%")
    else:
        print(f"{outcome:10} :     0 шт  →   0.0%")

print("-"*50)
print(f"Всего записей: {sum_all}")
print("="*50 + "\n")

==================================================
Статистика исходов (всего экспериментов: 369823)
==================================================
success    : 170682 шт  →   46.2%
drop       :  7873 шт  →    2.1%
crush      : 191268 шт  →   51.7%
marginal   :     0 шт  →   0.0%
--------------------------------------------------
Всего записей: 369823
==================================================

In [58]:
# выбрать только нужные колонки
columns = ["exp_id", "object_name", "grasp_force_N", "outcome"]
df_selected = df[columns]

print(df_selected.head(300))

     exp_id     object_name  grasp_force_N  outcome
0         1           Stone         32.342  success
1         2  Plastic bottle         34.543  success
2         3     Chicken egg         16.992    crush
3         4     Rubber ball         17.328    crush
4         5          Tomato          5.928    crush
..      ...             ...            ...      ...
295     296     Chicken egg         38.422    crush
296     297         Tin can        103.126  success
297     298     Chicken egg         38.628    crush
298     299  Plastic bottle        545.165    crush
299     300          Tomato          5.927    crush

[300 rows x 4 columns]

In [59]:
df.head(30)

,exp_id,object_name,shape_type,density,volume,mass,size_x,size_y,size_z,surface_area,...,transparency,hardness,grasp_force_N,contact_stress,stress_ratio,outcome,label_success,label_crush,label_drop,duration_sec
0,1,Stone,cube,2795.1,1.010000e-06,0.00283,0.01004,0.01004,0.01004,0.000604,...,opaque,7.0,32.342,70504.5,0.00082,success,1,0,0,8.65
1,2,Plastic bottle,cylinder,1444.2,1.675400e-03,2.41965,0.27434,0.08818,0.08818,0.088213,...,transparent,2.0,34.543,165487.3,0.60348,success,1,0,0,6.52
2,3,Chicken egg,ellipsoid,2050.2,1.553900e-04,0.31858,0.07807,0.04461,0.04461,0.020899,...,opaque,3.0,16.992,89008.9,1.84515,crush,0,1,0,3.19
3,4,Rubber ball,sphere,1335.6,2.319800e-04,0.30983,0.07623,0.07623,0.07623,0.018258,...,opaque,0.1,17.328,115276.7,2.71470,crush,0,1,0,2.94
4,5,Tomato,sphere,1074.3,2.290400e-04,0.24606,0.07591,0.07591,0.07591,0.018103,...,opaque,0.5,5.928,35681.3,1.17566,crush,0,1,0,0.78
5,6,Chicken egg,ellipsoid,2214.9,8.720000e-05,0.19315,0.06440,0.03680,0.03680,0.014219,...,opaque,3.0,16.845,89583.8,1.85084,crush,0,1,0,3.33
6,7,Chicken egg,ellipsoid,2413.0,1.426400e-04,0.34419,0.07588,0.04336,0.04336,0.019739,...,opaque,3.0,23.599,82720.8,1.56280,crush,0,1,0,2.68
7,8,Stone,cube,2823.1,1.010000e-06,0.00285,0.01003,0.01003,0.01003,0.000603,...,opaque,7.0,84.554,105004.8,0.00136,success,1,0,0,4.19
8,9,Stone,cube,2762.7,1.420000e-06,0.00393,0.01124,0.01124,0.01124,0.000758,...,opaque,7.0,88.768,128920.6,0.00157,success,1,0,0,3.83
9,10,Cucumber,cylinder,1001.2,1.591000e-04,0.15930,0.15410,0.03626,0.03626,0.019618,...,opaque,0.3,5.928,35233.0,1.18611,success,1,0,0,0.84
10,11,Tin can,cylinder,6932.1,3.915000e-04,2.71396,0.09804,0.07130,0.07130,0.029949,...,opaque,4.5,296.986,1214170.3,2.38791,crush,0,1,0,3.26
11,12,Stone,cube,2353.0,8.400000e-07,0.00199,0.00945,0.00945,0.00945,0.000536,...,opaque,7.0,72.540,81474.9,0.00092,success,1,0,0,4.06
12,13,Stone,cube,2660.5,1.340000e-06,0.00356,0.01102,0.01102,0.01102,0.000728,...,opaque,7.0,72.529,92896.3,0.00122,success,1,0,0,4.11
13,14,Plastic bottle,cylinder,1387.8,1.602970e-03,2.22463,0.27033,0.08689,0.08689,0.085652,...,transparent,2.0,1444.991,6784955.7,24.92611,crush,0,1,0,1.55
14,15,Tomato,sphere,898.4,2.992200e-04,0.26883,0.08298,0.08298,0.08298,0.021635,...,opaque,0.5,17.328,64165.0,1.65623,crush,0,1,0,2.95
15,16,Stone,cube,2388.6,8.400000e-07,0.00201,0.00943,0.00943,0.00943,0.000534,...,opaque,7.0,73.915,65788.7,0.00070,success,1,0,0,4.76
16,17,Tomato,sphere,994.6,2.295700e-04,0.22834,0.07597,0.07597,0.07597,0.018131,...,opaque,0.5,5.927,37794.3,1.32602,crush,0,1,0,0.88
17,18,Stone,cube,2386.4,9.400000e-07,0.00224,0.00980,0.00980,0.00980,0.000576,...,opaque,7.0,37.497,142076.9,0.00161,success,1,0,0,4.12
18,19,Chicken egg,ellipsoid,1930.4,7.267000e-05,0.14028,0.06060,0.03463,0.03463,0.012591,...,opaque,3.0,6.820,65897.4,1.29719,success,1,0,0,2.85
19,20,Chicken egg,ellipsoid,2109.6,1.574400e-04,0.33213,0.07841,0.04481,0.04481,0.021082,...,opaque,3.0,8.957,64203.4,1.26096,success,1,0,0,3.51
20,21,Stone,cube,2500.4,7.400000e-07,0.00185,0.00904,0.00904,0.00904,0.000490,...,opaque,7.0,74.916,62897.2,0.00070,success,1,0,0,5.92
21,22,Plastic bottle,cylinder,1528.6,1.112870e-03,1.70114,0.23937,0.07694,0.07694,0.067156,...,transparent,2.0,303.687,1314194.8,4.40210,crush,0,1,0,4.22
22,23,Tin can,cylinder,6678.7,7.367200e-04,4.92035,0.12104,0.08803,0.08803,0.045649,...,opaque,4.5,261.346,1156098.0,2.33497,crush,0,1,0,4.01
23,24,Plastic bottle,cylinder,1310.0,2.879950e-03,3.77275,0.32863,0.10563,0.10563,0.126584,...,transparent,2.0,147.681,789491.6,2.60804,crush,0,1,0,1.19
24,25,Chicken egg,ellipsoid,1878.0,1.622600e-04,0.30473,0.07921,0.04526,0.04526,0.021510,...,opaque,3.0,11.738,70013.8,1.51040,success,1,0,0,3.36
25,26,Tin can,cylinder,7292.3,6.624700e-04,4.83094,0.11683,0.08497,0.08497,0.042527,...,opaque,4.5,286.101,1792000.1,4.66687,crush,0,1,0,3.51
26,27,Plastic bottle,cylinder,1183.0,1.242450e-03,1.46983,0.24832,0.07982,0.07982,0.072273,...,transparent,2.0,107.342,750541.9,2.77573,crush,0,1,0,1.70
27,28,Plastic bottle,cylinder,1322.1,1.525550e-03,2.01688,0.26590,0.08547,0.08547,0.082871,...,transparent,2.0,1515.294,11788402.0,38.40307,crush,0,1,0,1.38
28,29,Plastic bottle,cylinder,1347.1,1.582360e-03,2.13163,0.26916,0.08652,0.08652,0.084916,...,transparent,2.0,100.719,629877.4,2.12022,crush,0,1,0,1.45
29,30,Tomato,sphere,888.8,1.171400e-04,0.10411,0.06071,0.06071,0.06071,0.011578,...,opaque,0.5,10.462,41032.5,1.65679,crush,0,1,0,0.87

In [60]:
df.tail(30)

,exp_id,object_name,shape_type,density,volume,mass,size_x,size_y,size_z,surface_area,...,transparency,hardness,grasp_force_N,contact_stress,stress_ratio,outcome,label_success,label_crush,label_drop,duration_sec
369798,369799,Chicken egg,ellipsoid,2997.8,9.835000e-05,0.29484,0.06703,0.03830,0.03830,0.015406,...,opaque,3.0,17.946,91188.1,1.68382,crush,0,1,0,1.46
369799,369800,Stone,cube,2829.1,7.000000e-07,0.00199,0.00889,0.00889,0.00889,0.000474,...,opaque,7.0,12.528,100609.0,0.00102,success,1,0,0,2.20
369800,369801,Rubber ball,sphere,1030.6,2.199400e-04,0.22666,0.07489,0.07489,0.07489,0.017620,...,opaque,0.1,17.328,76263.2,1.82458,success,1,0,0,1.61
369801,369802,Plastic bottle,cylinder,1591.3,1.330210e-03,2.11681,0.25403,0.08165,0.08165,0.075637,...,transparent,2.0,39.251,166477.5,0.56057,success,1,0,0,2.28
369802,369803,Plastic bottle,cylinder,1158.9,1.188050e-03,1.37688,0.24464,0.07863,0.07863,0.070147,...,transparent,2.0,39.157,166112.2,0.57706,success,1,0,0,2.27
369803,369804,Cucumber,cylinder,978.6,2.169300e-04,0.21228,0.17087,0.04021,0.04021,0.024122,...,opaque,0.3,17.328,82105.0,2.31241,crush,0,1,0,1.51
369804,369805,Stone,cube,2487.6,7.600000e-07,0.00189,0.00913,0.00913,0.00913,0.000500,...,opaque,7.0,93.150,89831.3,0.00108,success,1,0,0,2.38
369805,369806,Chicken egg,ellipsoid,2068.2,8.563000e-05,0.17710,0.06401,0.03658,0.03658,0.014047,...,opaque,3.0,15.846,72903.5,1.49227,crush,0,1,0,1.47
369806,369807,Plastic bottle,cylinder,1370.0,2.323850e-03,3.18368,0.30595,0.09834,0.09834,0.109713,...,transparent,2.0,496.656,3998454.5,12.71609,crush,0,1,0,0.67
369807,369808,Chicken egg,ellipsoid,2293.6,1.918600e-04,0.44004,0.08376,0.04786,0.04786,0.024052,...,opaque,3.0,26.628,83703.8,1.86124,crush,0,1,0,1.46
369808,369809,Chicken egg,ellipsoid,2577.6,9.448000e-05,0.24353,0.06614,0.03779,0.03779,0.014998,...,opaque,3.0,20.171,66486.7,1.39038,crush,0,1,0,1.40
369809,369810,Cucumber,cylinder,948.2,1.995900e-04,0.18926,0.16619,0.03910,0.03910,0.022818,...,opaque,0.3,5.928,28393.4,1.05109,success,1,0,0,0.46
369810,369811,Rubber ball,sphere,1062.9,2.443700e-04,0.25975,0.07757,0.07757,0.07757,0.018902,...,opaque,0.1,17.328,102656.3,2.51858,crush,0,1,0,1.53
369811,369812,Rubber ball,sphere,1091.2,2.982000e-04,0.32540,0.08289,0.08289,0.08289,0.021585,...,opaque,0.1,17.328,113933.3,2.75851,crush,0,1,0,2.10
369812,369813,Cucumber,cylinder,995.8,2.299700e-04,0.22901,0.17423,0.04099,0.04099,0.025078,...,opaque,0.3,5.927,48120.0,1.67767,crush,0,1,0,0.45
369813,369814,Rubber ball,sphere,1110.2,1.914100e-04,0.21251,0.07150,0.07150,0.07150,0.016062,...,opaque,0.1,17.328,72611.0,1.94845,success,1,0,0,1.65
369814,369815,Rubber ball,sphere,1039.6,2.055300e-04,0.21368,0.07322,0.07322,0.07322,0.016842,...,opaque,0.1,9.282,38870.8,1.01845,success,1,0,0,1.43
369815,369816,Tomato,sphere,1151.3,2.399100e-04,0.27621,0.07709,0.07709,0.07709,0.018672,...,opaque,0.5,8.287,39035.8,1.48007,crush,0,1,0,0.55
369816,369817,Plastic bottle,cylinder,1185.1,2.141570e-03,2.53790,0.29773,0.09570,0.09570,0.103899,...,transparent,2.0,189.145,1494428.1,4.52561,crush,0,1,0,0.84
369817,369818,Tin can,cylinder,8322.7,4.642200e-04,3.86361,0.10377,0.07547,0.07547,0.033551,...,opaque,4.5,79.542,503740.1,1.23640,success,1,0,0,1.60
369818,369819,Stone,cube,2820.6,1.540000e-06,0.00433,0.01154,0.01154,0.01154,0.000799,...,opaque,7.0,67.489,63214.6,0.00066,success,1,0,0,2.45
369819,369820,Chicken egg,ellipsoid,1972.6,1.613900e-04,0.31836,0.07907,0.04518,0.04518,0.021433,...,opaque,3.0,14.332,81622.7,1.42045,crush,0,1,0,1.73
369820,369821,Rubber ball,sphere,1020.6,2.552400e-04,0.26049,0.07870,0.07870,0.07870,0.019459,...,opaque,0.1,5.928,48859.9,1.13584,success,1,0,0,0.45
369821,369822,Rubber ball,sphere,911.2,1.176200e-04,0.10718,0.06079,0.06079,0.06079,0.011609,...,opaque,0.1,8.517,40491.1,1.14135,success,1,0,0,0.50
369822,369823,Tin can,cylinder,8329.5,5.649900e-04,4.70610,0.11079,0.08058,0.08058,0.038246,...,opaque,4.5,2004.094,16341141.5,39.88203,crush,0,1,0,1.55
369823,369824,Chicken egg,ellipsoid,2060.3,1.821600e-04,0.37529,0.08232,0.04704,0.04704,0.023234,...,opaque,3.0,16.071,64132.8,1.21155,crush,0,1,0,1.61
369824,369825,Cucumber,cylinder,1027.8,2.545900e-04,0.26167,0.18024,0.04241,0.04241,0.026838,...,opaque,0.3,17.325,82151.5,2.53856,crush,0,1,0,2.17
369825,369826,Rubber ball,sphere,849.8,1.651500e-04,0.14035,0.06807,0.06807,0.06807,0.014557,...,opaque,0.1,9.320,48375.5,1.21682,success,1,0,0,0.45
369826,369827,Plastic bottle,cylinder,1292.5,1.292290e-03,1.67025,0.25159,0.08087,0.08087,0.074192,...,transparent,2.0,34.003,204878.4,0.65559,success,1,0,0,2.39
369827,369828,Rubber ball,sphere,1029.3,2.712300e-04,0.27917,0.08031,0.08031,0.08031,0.020264,...,opaque,0.1,17.328,89572.9,1.98161,success,1,0,0,1.60

In [61]:
# Выберите нужные колонки
columns = ["exp_id", "object_name", "grasp_force_N", "outcome"]
df_selected = df[columns]

# Статистика по каждому объекту
stats = df_selected.groupby("object_name")["outcome"].value_counts().unstack(fill_value=0)
print(stats)

outcome         crush  drop  success
object_name
Chicken egg     42331   111    11429
Cucumber        31886     0    20731
Plastic bottle  35297  1343    16050
Rubber ball      7068     0    46369
Stone              23     0    52612
Tin can         27569  6419    17653
Tomato          47094     0     5838